### PR TITLE
Clean build on OSX

### PR DESCRIPTION
**Pull request by mbi**
Includes build instructions (issue #70) and a few fixes to get the build process to cope with Homebrew's curses installation.

Added `-fnested-functions` because nested functions are turned off by default on LLVM's gcc.

### CODE REVIEW

**Comment by tung** [comment]
I can refactor the one other place where inner functions are used so you won't have to provide that specific flag. Once you confirm that works, I'll merge this in.

**Comment by mbi** [comment]
Awesome, thanks.

**Comment by tung** [comment]
Alright, I've removed the last remaining inner function, as well as the need for math.h and libm: c0f5ace1f8b43ba7f3b298860430c30613433d47.

**Comment by tung** [comment]
Also, ENABLE_SERVER is now false by default for all builds, so you won't need it in the cmake command line any more.

**Comment by mbi** [comment]
Awesome, thanks, it now builds fine with clang (Apple's LLVM), too. I updated my PR.

**Pull request merged**
